# Generated by Django 4.2.7 on 2026-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('simulation_route', models.JSONField(blank=True, default=list, help_text='List of [lat, lng] coordinates for simulation')),
                ('is_streaming', models.BooleanField(default=False, help_text='Whether live tracking is currently streaming')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plate'], name='vehicles_ve_plate_f1ecfa_idx'), models.Index(fields=['status', '-created_at'], name='vehicles_ve_status_09cd90_idx')],
            },
        ),
    ]
