# Generated by Django 4.2.7 on 2026-01-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('SIMULATED', 'Simulated'), ('REAL', 'Real')], default='REAL', max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', '-recorded_at'], name='tracking_ve_vehicle_70981b_idx'), models.Index(fields=['recorded_at'], name='tracking_ve_recorde_5c0981_idx')],
            },
        ),
    ]
